/**
 * Describes the two shapes of an entity's attributes: how they are stored
 * (`select`) and how they are provided when inserting (`insert`).
 *
 * @typeParam Select - The attribute shape read from the database.
 * @typeParam Insert - The attribute shape accepted when inserting.
 */
export type Attributes<Select extends object = object, Insert extends object = object> = {
	select: Select;
	insert: Insert;
};

/**
 * A session row as stored by an {@link Adapter}.
 *
 * @typeParam A - The shape of the session attributes.
 */
export interface DatabaseSession<A extends object = object> {
	/** The session id, also the first part of the session token. */
	id: string;
	/** The id of the user this session belongs to. */
	userId: string;
	/** The hash of the session secret, never expose this. */
	secretHash: Uint8Array;
	/** When the session was created. */
	createdAt: Date;
	/** When the session was last verified. Used for inactivity-based expiry. */
	lastVerifiedAt: Date;
	/** Custom attributes stored alongside the base columns. */
	attributes: A;
}

/**
 * A user row as stored by an {@link Adapter}.
 *
 * @typeParam A - The shape of the user attributes.
 */
export interface DatabaseUser<A extends object = object> {
	/** The user id. */
	id: string;
	/** Custom attributes stored alongside the base column. */
	attributes: A;
}

/**
 * Error returned by {@link Adapter} methods when a database operation fails.
 *
 * Adapter methods never throw — they return an `AdapterError` instead. The
 * original error is available via {@link Error.cause}.
 */
export class AdapterError extends Error {
	override readonly name = "AdapterError";
	constructor(opt: { operation: string; cause: unknown }) {
		super(`Adapter operation "${opt.operation}" failed`, {
			cause: opt.cause,
		});
	}
}

/**
 * A database adapter used by nyx-auth to persist sessions and users.
 *
 * Implement this interface to support a new database, or use an existing
 * implementation such as {@link "@nyx-auth/drizzle-adapter"!DrizzleAdapter}.
 *
 * ### Conventions
 *
 * - Methods never throw — on failure they return an {@link AdapterError}.
 * - `deleteSessionById` / `deleteSessionsByUserId` return `true` when at
 *   least one row was deleted, `false` otherwise.
 * - `find*` methods return `null` when nothing matches.
 *
 * @typeParam A - Session {@link Attributes}.
 * @typeParam UA - User {@link Attributes}.
 */
export interface Adapter<A extends Attributes = Attributes, UA extends Attributes = Attributes> {
	/**
	 * Inserts a session and returns the stored row.
	 *
	 * @param session - The session to insert, without an id (one is generated by the caller).
	 * @returns The stored session, or an {@link AdapterError} on failure.
	 */
	insertSession(session: DatabaseSession<A["insert"]>): Promise<DatabaseSession<A["select"]> | AdapterError>;

	/**
	 * Updates a session by its id.
	 *
	 * @param sessionId - The id of the session to update.
	 * @param session - The fields to update.
	 * @returns `undefined` on success, or an {@link AdapterError} on failure.
	 */
	updateSessionbyId(
		sessionId: string,
		session: Partial<Omit<DatabaseSession<Partial<A["select"]>>, "id" | "userId">>
	): Promise<undefined | AdapterError>;

	/**
	 * Deletes a session by its id.
	 *
	 * @param sessionId - The id of the session to delete.
	 * @returns `true` if a session was deleted, `false` otherwise, or an {@link AdapterError} on failure.
	 */
	deleteSessionById(sessionId: string): Promise<boolean | AdapterError>;

	/**
	 * Deletes all sessions belonging to a user.
	 *
	 * @param userId - The id of the user whose sessions to delete.
	 * @returns `true` if at least one session was deleted, `false` otherwise, or an {@link AdapterError} on failure.
	 */
	deleteSessionsByUserId(userId: string): Promise<boolean | AdapterError>;

	/**
	 * Inserts a user and returns the stored row.
	 *
	 * @param user - The user to insert, without an id (one is generated by the caller).
	 * @returns The stored user, or an {@link AdapterError} on failure.
	 */
	insertUser(user: DatabaseUser<UA["insert"]>): Promise<DatabaseUser<UA["select"]> | AdapterError>;

	/**
	 * Fetches a user by its id.
	 *
	 * @param userId - The id of the user to fetch.
	 * @returns The user, `null` if no user with that id exists, or an {@link AdapterError} on failure.
	 */
	findUserById(userId: string): Promise<DatabaseUser<UA["select"]> | null | AdapterError>;

	/**
	 * Updates a user by its id.
	 *
	 * @param userId - The id of the user to update.
	 * @param user - The fields to update.
	 * @returns `undefined` on success, or an {@link AdapterError} on failure.
	 */
	updateUserbyId(userId: string, user: Partial<Omit<DatabaseUser<Partial<UA["select"]>>, "id">>): Promise<undefined | AdapterError>;

	/**
	 * Deletes a user by its id.
	 *
	 * @param userId - The id of the user to delete.
	 * @returns `undefined` on success, or an {@link AdapterError} on failure.
	 */
	deleteUserById(userId: string): Promise<undefined | AdapterError>;

	/**
	 * Fetches a session and its user by the session id.
	 *
	 * This is used by {@link SessionAPI.validateToken} and should join the
	 * session and user tables in a single query.
	 *
	 * @param sessionId - The id of the session to fetch.
	 * @returns The session and its user, `null` if the session does not exist, or an {@link AdapterError} on failure.
	 */
	findSessionWithUserById(
		sessionId: string
	): Promise<{ session: DatabaseSession<A["select"]>; user: DatabaseUser<UA["select"]> } | null | AdapterError>;
}
